import type { PlanEvent, WeekDay } from "./dashboard";

// Calendar-specific data on top of the dashboard's plan primitives: the
// two-week range builder, hand-authored per-day summaries (Mira's planner
// voice), and the recurring Saturday market (generated by weekday so it's
// always correct regardless of the visitor's real date — unlike a static
// dayOffset, which couldn't pin itself to "Saturday").

const DOW = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
const MONTH_ABBR = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

/**
 * Mono-caps section labels for the agenda: "This week" / "Next week", then
 * "Week of MMM D" computed from each later week's Monday. (CSS uppercases them
 * to match the THIS WEEK register.)
 */
export function weekSectionLabels(now: Date, count: number): string[] {
  const mondayIndex = (now.getDay() + 6) % 7;
  const labels: string[] = [];
  for (let w = 0; w < count; w++) {
    if (w === 0) {
      labels.push("This week");
    } else if (w === 1) {
      labels.push("Next week");
    } else {
      const d = new Date(now);
      d.setDate(now.getDate() + w * 7 - mondayIndex);
      labels.push(`Week of ${MONTH_ABBR[d.getMonth()]} ${d.getDate()}`);
    }
  }
  return labels;
}

/** `count` consecutive Mon–Sun weeks starting from the Monday of this week. */
export function buildWeeks(now: Date, count: number): WeekDay[][] {
  const mondayIndex = (now.getDay() + 6) % 7; // days from Monday to today
  const weeks: WeekDay[][] = [];
  for (let w = 0; w < count; w++) {
    const week: WeekDay[] = [];
    for (let i = 0; i < 7; i++) {
      const offset = w * 7 + i - mondayIndex;
      const d = new Date(now);
      d.setDate(now.getDate() + offset);
      week.push({
        offset,
        dayLabel: DOW[d.getDay()],
        dateLabel: String(d.getDate()),
        isToday: offset === 0,
        isPast: offset < 0,
      });
    }
    weeks.push(week);
  }
  return weeks;
}

// Hand-authored summaries for Mira's active days — the "written like a letter"
// planner voice. Keyed by dayOffset (stable: today is always 0), so they stay
// correct as the demo date moves. Days without one just show their chips.
const MIRA_SUMMARIES: Record<number, string> = {
  0: "Three pickups today, first at 4:30 — cut the zinnias in the cool before the heat climbs.",
  [-1]: "Lettuce pulled before it bolted; the last zinnias went to Tomás.",
  1: "No pickups — a day for the plot. Water deep before the heat wave lands.",
  2: "The heat sets in. One pickup; keep the beds shaded and watered.",
};

export function daySummaryFor(sellerId: string, dayOffset: number): string | null {
  if (sellerId !== "miras-half-acre") return null;
  return MIRA_SUMMARIES[dayOffset] ?? null;
}

/** A summary lookup for every offset in range — serializable for the client. */
export function daySummaries(sellerId: string, weeks: WeekDay[][]): Record<number, string> {
  const out: Record<number, string> = {};
  for (const day of weeks.flat()) {
    const summary = daySummaryFor(sellerId, day.offset);
    if (summary) out[day.offset] = summary;
  }
  return out;
}

/**
 * The recurring Saturday market as plan events on each Saturday in range.
 * Mira sells at the SFC market at Republic Square; other sellers get none.
 */
export function marketDaysFor(sellerId: string, weeks: WeekDay[][]): PlanEvent[] {
  if (sellerId !== "miras-half-acre") return [];
  return weeks
    .flat()
    .filter((d) => d.dayLabel === "Sat")
    .map((d) => ({ dayOffset: d.offset, label: "SFC market · 9–1", kind: "market" as const }));
}
